name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
      - 'feature/**'
      - 'feat/**'
      - 'release/**'
      - 'fix/**'
  pull_request:

defaults:
  run:
    working-directory: gitcidevB-main/eval-git-ci-js-base

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: gitcidevB-main/eval-git-ci-js-base/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: gitcidevB-main/eval-git-ci-js-base/reports/junit.xml
          if-no-files-found: ignore
